name: Cut Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    name: Cut New GitHub Release
    runs-on: depot-ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Create GitHub App token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        id: app-token
        with:
          app-id: ${{ secrets.PAPER_COMPUTE_CO_BOT_APP_ID }}
          private-key: ${{ secrets.PAPER_COMPUTE_CO_BOT_PRIVATE_KEY }}

      - name: Install Dagger
        uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644 # v8.2.0
        with:
          version: "0.21.7"

      - name: Create release via ghrelease
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        run: |
          dagger call -m github.com/papercomputeco/daggerverse/ghrelease@45e997aec734ec4875ff57bebed2317e1bd49185 \
              --token=env://GH_TOKEN \
            with-repo \
              --repo="${{ github.repository }}" \
            with-source \
              --source=. \
            create
